AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  StarAlignerBatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: StarAlignerFargateJobQueue
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref StarAlignerBatchComputeEnvironment
      State: ENABLED

  StarAlignerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "star-aligner-files-${AWS::AccountId}"

  StarAlignerJobDefinitionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: StarAlignerS3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt StarAlignerBucket.Arn
                  - !Sub "${StarAlignerBucket.Arn}/*"

  StarAlignerBatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: StarAlignerBatchComputeEnvironment
      Type: MANAGED
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 16
        Subnets:
          - subnet-0639d80feade9df54
          - subnet-02d9a3801a1a594c9
        SecurityGroupIds:
          - sg-0d680c8c9b336d91b

  StarAlignerBatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: StarAlignerfargateJob
      PlatformCapabilities:
        - FARGATE
      Type: Container
      ContainerProperties:
        Image: 975049994824.dkr.ecr.eu-north-1.amazonaws.com/star-aligner-repo-unique-3:v1.0
        ResourceRequirements:
          - Type: VCPU
            Value: "1"
          - Type: MEMORY
            Value: "2048"

        ExecutionRoleArn: !GetAtt StarAlignerJobDefinitionExecutionRole.Arn
        NetworkConfiguration:
          AssignPublicIp: ENABLED
        RuntimePlatform:
          OperatingSystemFamily: LINUX
          CpuArchitecture: X86_64
        Environment:
          - Name: BUCKET_NAME
            Value: !Ref StarAlignerBucket

  StarAlignerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: star-aligner-repo-unique-3
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: StarAligner
