AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  StarAlignerBatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: StarAlignerFargateJobQueue
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref StarAlignerBatchComputeEnvironment
      State: ENABLED

  StarAlignerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "star-aligner-files-${AWS::AccountId}"

  StarAlignerBatchExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - batch.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  StarAlignerBatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: StarAlignerComputeEnvironment
      Type: MANAGED
      ServiceRole: !GetAtt StarAlignerBatchExecutionRole.Arn
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 16
        Subnets:
          - subnet-0639d80feade9df54
          - subnet-02d9a3801a1a594c9
        SecurityGroupIds:
          - sg-0d680c8c9b336d91b

  StarAlignerBatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: StarAlignerfargateJob
      PlatformCapabilities:
        - FARGATE
      Type: Container
      ContainerProperties:
        Image: 975049994824.dkr.ecr.eu-north-1.amazonaws.com/star-aligner-repo:latest
        ResourceRequirements:
          - Type: VCPU
            Value: "1"
          - Type: MEMORY
            Value: "2048"
        Command:
          - "echo"
          - "hello world"
        ExecutionRoleArn: !GetAtt StarAlignerBatchExecutionRole.Arn
        NetworkConfiguration:
          AssignPublicIp: ENABLED

  StarAlignerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: star-aligner-repo-unique
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
